__title__ = 'wow'
__description__ = ''
__url__ = ''
__version__ = '1.2'
__author__ = 'Foebry'
__author_email__ = 'rain_fabry@hotmail.com'
__license__ = ''
__copyright__ = 'Copyright 2021 Sander Fabry'
